### ISSUE TITLE
PSA: new Gemfile dependency kramdown-parser-gfm

### ISSUE THREAD

**Issue by jonatack** [bitcoin-core-review-club/website#243] opened 2020-08-16 04:10 UTC
I'm currently using Ruby 2.6.6p146 (2020-03-31) with this repo (and so an updated `Gemfile.lock` as well), so this may or may not affect anyone using a different major version like Ruby 2.5.x, but here's a quick public service announcement, if helpful:

To run `make preview`, I needed to add the following line to the Gemfile and run `bundle update`:

```diff
diff --git a/Gemfile b/Gemfile
index 71b0ef9..52bd101 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,6 +8,7 @@ gem "jekyll-paginate", "~> 1.1"
 gem "jekyll-sitemap", "~> 1.3"
 gem "jekyll-feed", "~> 0.12.1"
 gem "jekyll-seo-tag", "~> 2.6"
+gem "kramdown-parser-gfm"
```

**Comment by jonatack** [comment] 2020-08-16 04:11
More details:
```
$ make clean preview
bundle exec jekyll clean
../..
  Incremental build: enabled
      Generating... 
             Error: YAML Exception reading /home/jon/projects/bitcoin/review-club/_posts/2020-07-22-#15644.md: (<unknown>): could not find expected ':' while scanning a simple key at line 9 column 1
       Jekyll Feed: Generating feed for posts
  Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2019-05-01-#15557.md':
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
make: *** [Makefile:9: preview] Error 1
```

**Comment by jonatack** [comment] 2020-08-16 04:12
More details:
```
$ make clean preview
bundle exec jekyll clean
../..
  Incremental build: enabled
      Generating... 
       Jekyll Feed: Generating feed for posts
  Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2019-05-01-#15557.md':
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
```

**Comment by jonatack** [comment] 2020-08-16 04:15
More details:
```
$ make clean preview
bundle exec jekyll clean
../..
       Jekyll Feed: Generating feed for posts
  Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies
  installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error
  message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find
  helpful resources at https://jekyllrb.com/help/! 
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
```

**Comment by jnewbery** [comment] 2020-08-20 09:44
Thanks Jon! I'm running ruby 2.5.1 and haven't had any problem running `make preview`. Do you think we need to make any changes here?

**Comment by jonatack** [comment] 2020-08-20 09:56
I think we're fine, this being a static site. When 2.5 is no longer supported (normally starting sometime between next Christmas Day when the annual major release comes out and April 2021) we may want to upgrade to 2.6. Source: https://www.ruby-lang.org/

**Comment by jnewbery** [comment] 2020-08-20 11:04
ok, thanks. I'll close this for now then and we can revisit when 2.5 is unsupported.

**Comment by jnewbery** [comment] 2020-09-14 12:55
@robot-dreams - is this the issue you were seeing?

**Comment by robot-dreams** [comment] 2020-09-15 07:14
This was exactly the issue I was seeing, but now I feel a little silly because I'm no longer able to reproduce it (even after uninstalling a bunch of gems, deleting the local repo and starting over with a fresh checkout)!

By the way, my ruby version:

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
```

Maybe we can reopen this issue if it comes up and I'm able to identify reproducible problematic steps?

**Comment by jonatack** [comment] 2020-09-15 07:17
You may see it again the next time you `bundle update` to a recent version of Jekyll that wants it.

**Comment by jonatack** [comment] 2020-09-15 07:23
(For better or worse, with Ruby libraries I'm in the habit of `gem update --system && gem update && bundle update` frequently, to minimize the pain of doing it after a long period with lots of breakage. But it was also because I was contributing frequently to the Ruby on Rails framework for a few years and was in the habit of fixing stuff on the bleeding edge.)

**Comment by robot-dreams** [comment] 2020-09-15 08:12
Thanks @jonatack, that's really helpful!

Confirmed that after doing `gem update --system && gem update && bundle update`, a subsequent `make clean preview` gives the same `kramdown-parser-gfm` error again.

**Comment by jonatack** [comment] 2020-09-15 08:15
Yup, easy to fix thankfully, just add that line to the Gemfile and `bundle update` and you're good to go.

**Comment by jnewbery** [comment] 2020-09-15 08:24
Sounds we increase the minimum ruby version to 2.6 and update the gentile in a PR?

**Comment by jonatack** [comment] 2020-09-15 08:28
According to https://www.ruby-lang.org/en/, 2.5.x support won't end until ~April 2021 and 2.6.6 is the current stable version of 2.6.

Every Christmas Day, a new annual major release comes out.

I use it with 2.6.6 at the moment, but probably no rush unless everyone else is on 2.6.

**Comment by jnewbery** [comment] 2020-09-15 10:44
I really don't mind bumping the min version. Only very few contributors actually build this project locally, and if bumping the min version saves time for new contributors by making sure they don't hit this issue, then it seems worthwhile.

**Comment by jonatack** [comment] 2020-09-15 10:51
SGTM--will do.

**Comment by jnewbery** [comment] 2021-05-28 12:07
@jonatack Ruby 2.5 is now EOL (https://www.ruby-lang.org/en/downloads/branches/). Should we bump min version to 2.6?

**Comment by jnewbery** [comment] 2021-06-01 12:51
Thanks @jonatack. Closing.

**Closed by jnewbery** 2021-06-01 12:51 UTC
